#!/usr/bin/python3

import sys


for arg in sys.argv[1:]:
    inpt = arg
if len(sys.argv) < 2:
    print('Kindly specify a value:')
    inpt = input("what is the subnet mask or cidr notation?\n")


def get_the_cidr():

    if inpt == '/0':
        print('''0.0.0.0
Max Hosts: 4294967296 ''')
    elif inpt == '0.0.0.0':
        print('''/0
Max Hosts: 4294967296 ''')
    elif inpt == '/1':
        print('''128.0.0.0
Max Hosts: 2147483648''')
    elif inpt == '128.0.0.0':
         print('''/1
Max Hosts: 2147483648''')
    elif inpt == '/2':
        print('''192.0.0.0
Max Hosts: 1073741824''')
    elif inpt == '192.0.0.0':
        print('''/2
Max Hosts: 1073741824''')
    elif inpt == '/3':
        print('''224.0.0.0
Max Hosts: 536870912''')
    elif inpt == '224.0.0.0':
        print('''/3
Max Hosts: 536870912''')
    elif inpt == '/4':
        print('''240.0.0.0
Max Hosts: 268435456''')
    elif inpt == '240.0.0.0':
        print('''/4
Max Hosts: 268435456''')
    elif inpt == '/5':
        print('''248.0.0.0
Max Hosts: 134217728''')
    elif inpt == '248.0.0.0':
        print('''/5
Max Hosts: 134217728''')
    elif inpt == '/6':
        print('''252.0.0.0
Max Hosts: 67108864''')
    elif inpt == '252.0.0.0':
        print('''/6
Max Hosts: 67108864''')
    elif inpt == '/7':
        print('''254.0.0.0
Max Hosts: 33554432''')
    elif inpt == '254.0.0.0':
        print('''/7
Max Hosts: 33554432''')
    elif inpt == '/8':
        print('''255.0.0.0
Max Hosts: 16777216''')
    elif inpt == '255.0.0.0':
        print('''/8
Max Hosts: 16777216''')
    elif inpt == '/9':
        print('''255.128.0.0
Max Hosts: 8388608''')
    elif inpt == '255.128.0.0':
        print('''/9
Max Hosts: 8388608''')
    elif inpt == '/10':
        print('''255.192.0.0
Max Hosts: 4194304''')
    elif inpt == '255.192.0.0':
        print('''/10
Max Hosts: 4194304''')
    elif inpt == '/11':
        print('''255.224.0.0
Max Hosts: 2097152''')
    elif inpt == '255.224.0.0':
        print('''/11
Max Hosts: 2097152''')
    elif inpt == '/12':
        print('''255.240.0.0
Max Hosts: 1048576''')
    elif inpt == '255.240.0.0':
        print('''/12
Max Hosts: 1048576''')
    elif inpt == '/13':
        print('''255.248.0.0
Max Hosts: 524288''')
    elif inpt == '255.248.0.0':
        print('''/13
Max Hosts: 524288''')
    elif inpt == '/14':
        print('''255.252.0.0
Max Hosts: 262144''')
    elif inpt == '255.252.0.0':
        print('''/14
Max Hosts: 262144''')
    elif inpt == '/15':
        print('''255.254.0.0
Max Hosts: 131072''')
    elif inpt == '255.254.0.0':
        print('''/15
Max Hosts: 131072''')
    elif inpt == '/16':
        print('''255.255.0.0
Max Hosts: 65536''')
    elif inpt == '255.255.0.0':
        print('''/16
Max Hosts: 65536''')
    elif inpt == '/17':
        print('''255.255.128.0
Max Hosts: 32768''')
    elif inpt == '255.255.128.0':
        print('''/17
Max Hosts: 32768''')
    elif inpt == '/18':
        print('''255.255.192.0
Max Hosts: 16384''')
    elif inpt == '255.255.192.0':
        print('''/18
Max Hosts: 16384''')
    elif inpt == '/19':
        print('''255.255.224.0
Max Hosts: 8192''')
    elif inpt == '255.255.224.0':
        print('''/19
Max Hosts: 8192''')
    elif inpt == '/20':
        print('''255.255.240.0
Max Hosts: 4096''')
    elif inpt == '255.255.240.0':
        print('''/20
Max Hosts: 4096''')
    elif inpt == '/21':
        print('''255.255.248.0
Max Hosts: 2048''')
    elif inpt == '255.255.248.0':
        print('''/21
Max Hosts: 2048''')
    elif inpt == '/22':
        print('''255.255.252.0
Max Hosts: 1024''')
    elif inpt == '255.255.252.0':
        print('''/22
Max Hosts: 1024''')
    elif inpt == '/23':
        print('''255.255.254.0
Max Hosts: 512''')
    elif inpt == '255.255.254.0':
        print('''/23
Max Hosts: 512''')
    elif inpt == '/24':
        print('''255.255.255.0
Max Hosts: 256''')
    elif inpt == '255.255.255.0':
        print('''/24
Max Hosts: 256''')
    elif inpt == '/25':
        print('''255.255.255.128
Max Hosts: 128''')
    elif inpt == '255.255.255.128':
        print('''/25
Max Hosts: 128''')
    elif inpt == '/26':
        print('''255.255.255.192
Max Hosts: 64 ''')
    elif inpt == '255.255.255.192':
        print('''/26
Max Hosts: 64 ''')
    elif inpt == '/27':
        print('''255.255.255.224
Max Hosts: 32''')
    elif inpt == '255.255.255.224':
        print ('''/27
Max Hosts: 32''')
    elif inpt == '/28':
        print('''255.255.255.240
Max Hosts: 16''')
    elif inpt == '255.255.255.240':
        print('''/28
Max Hosts: 16''')
    elif inpt == '/29':
        print('''255.255.255.248
Max Hosts: 8''')
    elif inpt == '255.255.255.248':
        print('''/29
Max Hosts: 8''')
    elif inpt == '/30':
        print('''255.255.255.252
Max Hosts: 4''')
    elif inpt == '255.255.255.252':
        print('''/30
Max Hosts: 4''')
    elif inpt == '/31':
        print('''255.255.255.254
Max Hosts: 2''')
    elif inpt == '255.255.255.254':
        print('''/31
Max Hosts: 2''')
    elif inpt == '/32':
        print('''255.255.255.255
Single host: 1''')
    elif inpt == '255.255.255.255':
        print('''/32
Single Host: 1''')
    else:
        print('''This is NOT a valid subnetmask.
        
        Kindly type the cidr notation with a '/' and the range can be from /0 through /32
        or
        insert regular subnet mask with (.) seperated octates, such as xxx.xxx.xxx.xxx''')
        exit()
        get_the_cidr()

get_the_cidr()
